### ISSUE TITLE
docker-compose.yml如何配置，我的配置提示invalid_api_key

### ISSUE THREAD

**Issue by GeekWorkCode** [duo/wechatgpt#1]
这样配置对吗？提示invalid_api_key
version: '3'
services:
  wechatgpt:
    restart: always
    container_name: wechatgpt
    image: lxduo/wechatgpt
    environment:
      - SESSION_TOKEN=chrome开发者模式抓取的SESSION_TOKEN
      - SESSION_TOKEN=120
      - AUTO_ACCEPT=fals

**Comment by duo** [comment]
`SESSION_TOKEN=120` ?

**Comment by GeekWorkCode** [comment]
> `SESSION_TOKEN=120` ?

好吧复制粘贴导致的低价错误。。。换成- TASK_TIMEOUT=120s 还是提示Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.\",\"type\":\"invalid_request_error\",\"param\":null,\"code\":\"invalid_api_key\"}}"
你这个是用的需要扣费的API key  还是网页开发者工具里面抓取的__Secure-next-auth.session-token呢

**Comment by duo** [comment]
`__Secure-next-auth.session-token`, 暴长的那个...

**Comment by GeekWorkCode** [comment]
> `__Secure-next-auth.session-token`, 暴长的那个...

version: '3'
  
services:
  wechatgpt:
    restart: always
    container_name: wechatgpt
    image: lxduo/wechatgpt
    environment:
      - SESSION_TOKEN=eyJhbGciOiJkaXIiLCJlbmb爆长
      - TASK_TIMEOUT=120s
      - AUTO_ACCEPT=false
